<?php

declare(strict_types=1);

namespace Jessecruz\LaravelResendInbox\Actions;

use Illuminate\Database\UniqueConstraintViolationException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Jessecruz\LaravelResendInbox\Events\InboxEmailReceived;
use Jessecruz\LaravelResendInbox\Models\InboxMessage;
use Jessecruz\LaravelResendInbox\Models\InboxThread;
use Jessecruz\LaravelResendInbox\Support\InboxConfig;
use Jessecruz\ResendInbox\Direction;
use Jessecruz\ResendInbox\EmailAddress;
use Jessecruz\ResendInbox\Exceptions\MailboxException;
use Jessecruz\ResendInbox\ResendMailbox;
use Jessecruz\ResendInbox\Threading\ThreadResolver;

final readonly class StoreReceivedEmail
{
    public function __construct(
        private ResendMailbox $resend,
        private ThreadResolver $threads,
    ) {}

    /**
     * Fetch the full inbound email from Resend, file it into its
     * conversation (reopening it as unread) and dispatch InboxEmailReceived
     * unless it is machine-generated. Idempotent per Resend email id, so
     * webhook redeliveries store and notify once. Mail addressed to another
     * domain on the same Resend account is dropped and returns null.
     *
     * @throws MailboxException
     */
    public function handle(string $resendId): ?InboxMessage
    {
        $existing = InboxMessage::query()->where('resend_id', $resendId)->first();

        if ($existing !== null) {
            return $existing;
        }

        $received = $this->resend->receivedEmail($resendId);
        $mailbox = InboxConfig::mailbox();
        $recipients = $received->recipients();

        if (! $mailbox->hasOwnRecipient($recipients)) {
            Log::info("Ignoring received email [{$resendId}]: no recipient on {$mailbox->domain}.", [
                'recipients' => array_map(EmailAddress::address(...), $recipients),
            ]);

            return null;
        }

        $address = $mailbox->mailboxFor($recipients);

        try {
            $message = DB::transaction(function () use ($received, $address): InboxMessage {
                $threadId = $this->threads->resolveFor($received);

                $thread = ($threadId !== null ? InboxThread::query()->find($threadId) : null)
                    ?? InboxThread::query()->create([
                        'subject' => $received->subject,
                        'mailbox' => $address,
                        'last_message_at' => $received->receivedAt,
                    ]);

                $inReplyTo = $received->inReplyTo();
                $references = $received->references();

                $message = $thread->messages()->create([
                    'direction' => Direction::Inbound,
                    'resend_id' => $received->resendId,
                    'message_id' => $received->messageId,
                    'in_reply_to' => $inReplyTo[0] ?? null,
                    'references' => $references !== [] ? implode(' ', $references) : null,
                    'mailbox' => $address,
                    'from_address' => $received->fromAddress,
                    'from_name' => $received->fromName,
                    'to' => $received->to,
                    'cc' => $received->cc,
                    'reply_to' => $received->replyTo,
                    'subject' => $received->subject,
                    'html' => $received->html,
                    'text' => $received->text,
                    'headers' => $received->headers,
                    'attachments' => $received->attachments,
                    'sent_at' => $received->receivedAt,
                ]);

                $thread->update([
                    'mailbox' => $address,
                    'last_message_at' => $thread->last_message_at->max($received->receivedAt),
                    'read_at' => null,
                    'archived_at' => null,
                ]);

                return $message;
            });
        } catch (UniqueConstraintViolationException) {
            return InboxMessage::query()->where('resend_id', $resendId)->firstOrFail();
        }

        if (! $received->isAutoGenerated()) {
            InboxEmailReceived::dispatch($message);
        }

        return $message;
    }
}
